### ISSUE TITLE
how to allow multiple short urls for same long url

### ISSUE THREAD

**Issue by vishals321** [cydrobolt/polr#127]
Please tell me how to allow multiple short urls for same long url?

**Comment by cydrobolt** [comment]
This is a bit difficult right now, since it isn't an option we've implemented.

However, there are some workarounds. For instance, you can add hash symbols (`#`) to force Polr to create a new short link. You can also toggle the "private" option in Link Options to force a new short URL. 

This might be a good option to implement in 2.0, so I will add it to the milestone.

Thanks for the report!
