### ISSUE TITLE
Fallback redirect

### ISSUE THREAD

**Issue by hanoii** [cydrobolt/polr#187]
It would be awesome if you'd have an alternative redirect configuration, which could be globally. Such as if a certain shorten is not found, then redirect to some other site.

I am moving away from bit.ly and was using a branded domain (my own) so I will be using that one to host my own shortener but I somehow want to allow previous shortened ids to work.

So I would like to being able redirect polr/xyz1234 to bit.ly/xyz1234.

Is this something easy to do? Would it have to be contributed on the code or is there any plugin specification?

Thanks,
Ariel.=

**Comment by cydrobolt** [comment]
Hi @hanoii!

This is a great idea to implement as a feature! Although there isn't currently an option in the setup, you can edit the Polr code to implement your feature. We're hoping to release a full plugin API soon. 

If no link is found, this code is run: https://github.com/cydrobolt/polr/blob/master/app/Http/Controllers/LinkController.php#L52

Instead of `return abort(404)`, you can instead have it redirect to a different link. You can try something like this instead:

```php
if ($link == null) {
    return redirect()->to('http://bit.ly/' . $short_url);
}
```

where `$short_url` represents the ending (e.g polr.me/<ending>)
