### ISSUE TITLE
Password Reset Form Will Not Submit

### ISSUE THREAD

**Issue by philip-ulrich** [cydrobolt/polr#267]
## Expected Behavior
Form should submit and password should get reset

## Current Behavior
Form will not submit

## Possible Solution
Can forms work without an action? It looks like it doesn't have one..
```
<div class="col-md-6 col-md-offset-3">
    <form method="POST" class="ng-pristine ng-valid ng-submitted">
        <input type="password" id="passwordFirst" placeholder="New Password" class="form-control password-input-pd">
        <input type="password" id="passwordConfirm" placeholder="Confirm New Password" class="form-control password-input-pd" name="new_password">

        <input type="hidden" name="_token" value="token">
        <input type="submit" id="submitForm" value="Reset Password" class="form-control">
    </form>
</div>
```

## Steps to Reproduce (for bugs)
1. Create account on https://z3r0.tech
2. Forget your password
3. Try to reset
4. Click link in email
5. Put in new password and try to click button. Nothing happens.

## Context
Can't reset password

## Your Environment
* Version or latest commit hash (`git rev-parse HEAD`):
9541ce83e0bbe4745f63a6f8630ee3fb29b102ea
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc):
Chrome 55 (and Safari in iOS 10)
php-fpm -v
PHP 5.6.28 (fpm-fcgi) (built: Nov 10 2016 16:15:52)

**Comment by cydrobolt** [comment]
I just tried and the fork submitted fine for me. Although I haven't received a reset email yet, I got the toast notification saying the reset email was sent. 

Have you tried using a new user?

**Comment by cydrobolt** [comment]
Oops, my bad. The actual password change from does seem to be bugged out. 

The form should be submitting to itself (same page as form is on)

It's possible that Angular is overwriting the action

**Comment by cydrobolt** [comment]
I think I've located the source of the bug. Since the reset password page hasn't been touched since before Angular was implemented throughout the app, Angular seems to have a weird default behavior of preventing "old-school" form submissions unless the action attribute is non-empty. 

Although it is valid to have a form without an action attribute (submits to self), Angular prevents this behavior. See https://docs.angularjs.org/api/ng/directive/ngSubmit

I've committed a fix in 9a420b4ccf468e6c5e25636167d34ab4ae831d93
Could you try pulling and seeing if this solves your problem?

**Comment by philip-ulrich** [comment]
Sure. Give me a few and I'll report back.

**Comment by philip-ulrich** [comment]
That works. Thanks for the prompt response.
