### ISSUE TITLE
[Feature Request] Sorting on the Admin Panel

### ISSUE THREAD

**Issue by Flare183** [cydrobolt/polr#86]
I would like to be able to sort the IP's and what not on the Admin panel. It would help to manage some abusive users. Thanks

**Comment by Cydrobolt** [comment]
Hmm, that sounds interesting. Perhaps a "search by ip" function might be helpful. Thanks for the suggestion, will try to implement it in 2.0. 

For now, you can always sort by IP using PHPMyAdmin or some other MySQL administration tool.

**Comment by robpomeroy** [comment]
I've found the datatables jQuery library a relatively straightforward way to add pagination, searching and sorting, client side, for a quick fix: http://holt59.github.io/datatable/

**Comment by cydrobolt** [comment]
@robpomeroy we've considered this option, but I'm not sure how great this would be with a large data set. DataTables requires that all the data be loaded onto the page at once. With a very large dataset, how would the browser handle it? Would the library be able to sort 500k+ links? Would the server become slowed if 500k rows were requested at once?

The current pagination system relies on serving one page at a time rather than serving all the data at once, which helps prevent slowdowns with a larger set of links.

**Comment by robpomeroy** [comment]
The trick would be to use Ajax requests to limit the results (see the "Ajax data" section on the Datatable introductory page).

**Comment by cydrobolt** [comment]
Oh, that's an interesting idea. Have you also taken a look at the other Datatables?
https://datatables.net/

It seems to be similar but more developed. If the Datatables library can make AJAX requests with needed information to render bits of information at a time, that would be the perfect solution. I'll look into this.

**Comment by overint** [comment]
Yep, datatables can load data page by page with ajax. It's pretty easy to implement the pagination in laravel, but the search is a bit more complex. There seems to be a bridge package:
https://github.com/yajra/laravel-datatables
