### ISSUE TITLE
Little feedback after first installation

### ISSUE THREAD

**Issue by mhow2** [Cydrobolt/polr#90]
Hi,

The installation runs fine. Great software. I just noticed some errors like :

    Warning: session_start(): Cannot send session cache limiter - headers already sent (output started   at /var/www/x/polr/layout-headermd.php:19) in /var/www/x/polr/lib-core.php on line 41

Also, the only ways to change running configuration (like subscription mode or any setting) are 1) run setup again, but in this case you have to re-fill all the fields once again 2) edit config.php but parameters are not documented anywhere. Actually I had to look the source of the setup form to get those.

No way to add/remove users in the UI from the admin account.

**Comment by Cydrobolt** [comment]
Thanks for the feedback! I think we may consider adding the user deletion feature. It sounds pretty useful.

As for the errors you are seeing, you they are completely normal. Since you are using this in production, you should disable error/warning display. Otherwise, sensitive data can be stolen. Let me know if you need help doing that.

**Comment by mhow2** [comment]
Thanks to you. And what about running configuration update remarks ?

**Comment by Cydrobolt** [comment]
I will keep them in mind, if you could create another ticket for those specific issues that would be great!
